name: ci

env:
  R2V: 5.9.8

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  r2git:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Installing radare2 from git
      run: ( git clone --depth=1 https://github.com/radareorg/radare2 && cd radare2 && sys/install.sh /usr )
    - name: Building radare2-mcp
      run: make
    - name: Testing radare2-mcp
      run: make test

  linux-deb:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Installing radare2 from deb
      run: |
        wget https://github.com/radareorg/radare2/releases/download/${{env.R2V}}/radare2_${{env.R2V}}_amd64.deb
        wget https://github.com/radareorg/radare2/releases/download/${{env.R2V}}/radare2-dev_${{env.R2V}}_amd64.deb
        sudo dpkg -i *.deb
    - name: Building radare2-mcp
      run: make
    - name: Testing radare2-mcp
      run: make test

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]
    env:
      ARCH: ${{ matrix.arch }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cloning radare2
      run: git clone --depth=1 --branch "${{env.R2V}}" https://github.com/radareorg/radare2
    - name: Building and installing radare2
      run: |
        cd radare2
        sys/install.sh
    - name: Building radare2-mcp
      run: make
    - name: Testing radare2-mcp
      run: make test